#!/bin/bash

say() {
    tput setaf 4
    echo -n " :: "
    tput sgr0
    echo "$1"
}

# save ans to $2
ask() {
    tput setaf 3
    echo -n " -> "
    tput sgr0
    echo -n "$1  "
    read $2
}

yell() {
    tput setaf 1
    echo -n " !! "
    tput sgr0
    echo "$1"
    exit
}

prepare_disks() {
    : > "$FSTAB"
    for line in $(cat "$FS"); do
        local part="$(echo "$line" | cut -d : -f 1)"
        local lbl="$(echo "$line" | cut -d : -f 2)"
        local action="$(echo "$line" | cut -d : -f 3)"

        if [[ "$lbl" == swap ]]; then
            swapoff "$part"
            mkswap -L swap "$part" || yell "sai can't format $part as swap"
            swapon "$part"

            echo "/dev/disk/by-label/swap swap swap defaults 0 0" >> "$FSTAB"
        else
            # run it before; umount to format again
            if grep -qs "$part" /proc/mounts; then
                umount "$part"
            fi
            if [[ "$action" == format ]]; then
                mkfs.ext4 "$part" || yell "sai can't format '$part' as ext4"
            fi
            e2label "$part" "$lbl"

            # mount it for install and generate fstab
            if [[ "$lbl" == root ]]; then
                mount -t ext4 "$part" /mnt || yell "sai can't mount $part as 'root'"

                echo "/dev/disk/by-label/root / ext4 defaults,noatime 0 1" >> "$FSTAB"
            else
                mkdir -p "/mnt/$lbl"
                mount -t ext4 "$part" "/mnt/$lbl" || yell "sai can't mount $part as '$lbl'"

                echo "/dev/disk/by-label/$lbl /$lbl ext4 defaults,noatime 0 2" >> "$FSTAB"
            fi
        fi
    done
}

find_disks() {
    find /dev/ -name "sd[a-z]" | cut -d / -f 3
}

find_parts() {
    find /dev/ -name "sd[a-z][1-9]" | cut -d / -f 3
}

get_size() {
    fdisk -l "$1" 2>/dev/null | sed -n 2p | cut -d , -f 1 | cut -d ' ' -f 3,4
}

avail_disks() {
    for disk in $(find_disks); do
        echo "$disk: $(get_size "/dev/$disk")"
    done
}

avail_parts() {
    for part in $(find_parts); do
        echo "$part: $(get_size "/dev/$part")"
    done
}

ask_part() {
    while true; do
        tput rev
        avail_disks
        tput sgr0

        ask "select a disk to partition? (type 'no' to skip)" disk
        if [[ "$disk" == no ]]; then
            break
        fi
        if [[ -b "/dev/$disk" ]]; then
            parted "/dev/$disk"
        else
            say "sai can't find device: '/dev/$disk'"
        fi
    done
}

ask_mkfs() {
    : > "$FS"
    tput rev
    avail_parts
    tput sgr0

    # root
    while true; do
        ask "select a partition for 'root'? (format)" dev
        if [[ -b "/dev/$dev" ]]; then
            break
        fi
    done
    echo "/dev/$dev:root:format" >> "$FS"
    # other
    for lbl in boot swap home; do
        while true; do
            ask "select a partition for '$lbl'? (type 'no' if you don't need it)" dev
            if [[ -b "/dev/$dev" || "$dev" == no ]]; then
                break
            fi
        done
        if [[ "$dev" == no ]]; then
            continue
        fi
        while true; do
            ask "format or mount $dev? [format | mount]" action
            if [[ "$action" == format || "$action" == mount ]]; then
                break
            fi
        done
        echo "/dev/$dev:$lbl:$action" >> "$FS"
    done
}

# chroot_mount()
# prepares target system as a chroot
#
chroot_mount() {
    mkdir -p /mnt/sys /mnt/proc /mnt/dev
    mount -t sysfs sysfs /mnt/sys 2>/dev/null
    mount -t proc proc /mnt/proc 2>/dev/null
    mount -o bind /dev /mnt/dev 2>/dev/null
    trap "chroot_umount" EXIT
}

# chroot_umount()
# tears down chroot in target system
#
chroot_umount() {
    umount -l /mnt/sys /mnt/proc /mnt/dev
}

gen_pacman_mirror() {
    wget -O /etc/pacman.d/mirrorlist 'https://www.archlinux.org/mirrorlist/?country=all&protocol=http&use_mirror_status=on'
    sed -i "s/#Server/Server/g" /etc/pacman.d/mirrorlist
}

pacman_install() {
    # update mirrorlist
    gen_pacman_mirror

    # prepare pacman environment
    mkdir -p /mnt/var/lib/pacman /mnt/var/cache/pacman/pkg
    while true; do
        pacman --root /mnt --cachedir /mnt/var/cache/pacman/pkg --noconfirm --needed \
            -Sy $(grep -v ^# /sai/packages.list)
        pacman_success=$?
        if [[ $pacman_success == 0 ]]; then
            # use the latest mirrorlist
            cp /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist
            break
        else
            ask "pacman has some problems. try again? (type 'no' to skip)" retry
            if [[ "$retry" == no ]]; then
                yell "sai stopped pacman"
            fi
        fi
    done
}

gen_syslinux_menu() {
    cp /sai/splash.jpg /mnt/boot/syslinux/
    cp /sai/syslinux.cfg /mnt/boot/syslinux/
}

gen_fstab() {
    # fstab is generated in "prepare_disks"
    cat "$FSTAB" >> /mnt/etc/fstab
}

sai_clean() {
    umount -l /mnt
    rm /tmp/sai_*
}
